# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/Cobbie/git/small-cpp-project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/Cobbie/git/small-cpp-project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/Cobbie/git/small-cpp-project/CMakeFiles /mnt/c/Users/Cobbie/git/small-cpp-project//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/Cobbie/git/small-cpp-project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CppDemo

# Build rule for target.
CppDemo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CppDemo
.PHONY : CppDemo

# fast build rule for target.
CppDemo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppDemo.dir/build.make CMakeFiles/CppDemo.dir/build
.PHONY : CppDemo/fast

#=============================================================================
# Target rules for targets named Graph

# Build rule for target.
Graph: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Graph
.PHONY : Graph

# fast build rule for target.
Graph/fast:
	$(MAKE) $(MAKESILENT) -f Graph/CMakeFiles/Graph.dir/build.make Graph/CMakeFiles/Graph.dir/build
.PHONY : Graph/fast

#=============================================================================
# Target rules for targets named Vertex

# Build rule for target.
Vertex: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Vertex
.PHONY : Vertex

# fast build rule for target.
Vertex/fast:
	$(MAKE) $(MAKESILENT) -f Graph/CMakeFiles/Vertex.dir/build.make Graph/CMakeFiles/Vertex.dir/build
.PHONY : Vertex/fast

#=============================================================================
# Target rules for targets named GeometricShapes

# Build rule for target.
GeometricShapes: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GeometricShapes
.PHONY : GeometricShapes

# fast build rule for target.
GeometricShapes/fast:
	$(MAKE) $(MAKESILENT) -f GeometricShapes/CMakeFiles/GeometricShapes.dir/build.make GeometricShapes/CMakeFiles/GeometricShapes.dir/build
.PHONY : GeometricShapes/fast

#=============================================================================
# Target rules for targets named Rectangle

# Build rule for target.
Rectangle: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Rectangle
.PHONY : Rectangle

# fast build rule for target.
Rectangle/fast:
	$(MAKE) $(MAKESILENT) -f GeometricShapes/CMakeFiles/Rectangle.dir/build.make GeometricShapes/CMakeFiles/Rectangle.dir/build
.PHONY : Rectangle/fast

#=============================================================================
# Target rules for targets named Triangle

# Build rule for target.
Triangle: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Triangle
.PHONY : Triangle

# fast build rule for target.
Triangle/fast:
	$(MAKE) $(MAKESILENT) -f GeometricShapes/CMakeFiles/Triangle.dir/build.make GeometricShapes/CMakeFiles/Triangle.dir/build
.PHONY : Triangle/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppDemo.dir/build.make CMakeFiles/CppDemo.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppDemo.dir/build.make CMakeFiles/CppDemo.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppDemo.dir/build.make CMakeFiles/CppDemo.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... CppDemo"
	@echo "... GeometricShapes"
	@echo "... Graph"
	@echo "... Rectangle"
	@echo "... Triangle"
	@echo "... Vertex"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

